version: "3.9"

services:
  backend:
    build: 
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/node_modules:/app/node_modules
    environment:
      - PORT=8000
    command: npm run dev