version: "3.9"

services:
  frontend:
    build: 
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - '80:3000'
    environment:
      - BUILD_DATE=${BUILD_DATE}
      - NODE_ENV=production
      # - NODE_ENV=development
      # - WATCHPACK_POLLING=true
      # - CHOKIDAR_USEPOLLING=true
    # volumes:
    #   - ./frontend:/frontend
    #   - ./frontend/node_modules:/frontend/node_modules
    #   - ./frontend/.next:/frontend/.next
    command: npm start
    # command: npm run dev
  backend:
    depends_on:
      - mongodb
    build: 
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - "8000:8000"
    # volumes:
    #   - ./backend:/backend
    #   - ./backend/node_modules:/backend/node_modules
    environment:
      - PORT=8000
      # - NODE_ENV=development
      - NODE_ENV=production
      - CRYPTO_KEY=d0851b59f3eed1b0befd75d296531f31033d5a29638e621c945266f3ffe053d2
      - JWT_PRIVATE_KEY=b7635fb72060431f0c5e59b027eed90bb3ba488740886a9da58d2cd0b506f3d3
    # command: npm run dev
    command: npm start
  mongodb:
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/database
volumes:
  dbdata: